name = "givesendgo-gala"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "gala-db"
database_id = "06464ea3-11a9-4df4-ba0d-0721f2c4230d"
