name = "givesendgo-gala"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "gala-db"
database_id = "ef69bfe1-70a2-4a31-b12f-f668240b34ef"
